language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

before_script:
  - cd ./Tests/Resources/
  - unzip people.json.zip
  - cd ../../
  - composer install --prefer-source

script:
  phpunit --bootstrap ./Tests/Unit/Bootstrap.php ./Tests/Unit

#git:
#  depth: 5
