language: php

dist: trusty

php:
  - 7.1
  - hhvm
  - nightly

env:
  - WITH_TWIG=yes
  - WITH_TWIG=no

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

before_script:
  - cd ./Tests/Resources/
  - unzip people.json.zip
  - cd ../../
  - composer install --prefer-source --ignore-platform-reqs
  - >
    if [[ "$WITH_TWIG" == "yes" ]]; then
      composer require twig/twig '^1.23';
    fi


script:
  - >
    export STAIRTOWER_TEST_SERVER_STARTUP_WAIT_TIME=2;
    export STAIRTOWER_TEST_SERVER_SHUTDOWN_WAIT_TIME=4;
    phpunit -c phpunit.xml
